package com.myspace.offermanagement.customerModel;
/**
 * This class was automatically generated by the data modeler tool.
 */


public class CustomerModel implements java.io.Serializable {



	static final long serialVersionUID = 1L;

	private Double age;
	private java.lang.String custId;
	private Double income;
	private java.lang.String customerClass;

	public Double getAge() {
		return age;
	}

	public void setAge(Double age) {
		this.age = age;
	}

	public String getCustId() {
		return custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public Double getIncome() {
		return income;
	}

	public void setIncome(Double income) {
		this.income = income;
	}

	public String getCustomerClass() {
		return customerClass;
	}

	public void setCustomerClass(String customerClass) {
		this.customerClass = customerClass;
	}
}