package com.myspace.offermanagement.customerModel;
/**
 * This class was automatically generated by the data modeler tool.
 */


public class PastHistoryModel implements java.io.Serializable {



    static final long serialVersionUID = 1L;

    private java.lang.String qualifiedPurchases;
    private java.lang.Integer lastOfferResponse;
    private String custId;

    public String getCustId() {
        return custId;
    }

    public void setCustId(String custId) {
        this.custId = custId;
    }

    public String getQualifiedPurchases() {
        return qualifiedPurchases;
    }

    public void setQualifiedPurchases(String qualifiedPurchases) {
        this.qualifiedPurchases = qualifiedPurchases;
    }

    public Integer getLastOfferResponse() {
        return lastOfferResponse;
    }

    public void setLastOfferResponse(Integer lastOfferResponse) {
        this.lastOfferResponse = lastOfferResponse;
    }
}